plugin: yc_compute
folders:
  - ab..c
auth_kind: serviceaccountfile
service_account_file: ../key.json
hostnames:
  - "{{name}}"
compose:
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address
